yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        null=True,
        blank=True,
    )

"""
в каждом объекте модели User автоматически будет создано свойство с таким же названием (posts), и в нём будут храниться ссылки на все объекты модели Post, которые ссылаются на объект User.
На практике это означает, что в объекте записи есть поле author, в котором хранится ссылка на автора (например, на пользователя admin), а в объекте пользователя admin появилось поле posts, в котором хранятся ссылки на все посты этого автора. И теперь можно получить список постов автора, обратившись к его свойству posts.
"""

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group


# Главная страница
def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    template = 'posts/index.html'
    context = {
        "posts": posts,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)

yatube/templates/base.html
{% load static %}

<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru" data-bs-theme="dark"> <!-- Язык сайта - русский, тема - тёмная -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180"
        href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32"
        href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16"
        href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
    <!-- скрипт смены тёмной и светлой тем -->
    <script>
      function myFunction() {
        var element = document.body;
        element.dataset.bsTheme =
          element.dataset.bsTheme == "light" ? "dark" : "light";
      }
      function stepFunction(event) {
        debugger;
        var element = document.getElementsByClassName("collapse");
        for (var i = 0; i < element.length; i++) {
          if (element[i] !== event.target.ariaControls) {
            element[i].classList.remove("show");
          }
        }
      }
    </script>
    <title>{% block title %} YaTube default heading {% endblock %}</title>
  </head>
  <body>
    <div class="container">
        <header>
          {% include 'includes/header.html' %}
        </header>
        <main> 
          {% block content %}
          {% endblock %}
        </main>
        <!-- Использованы классы бустрапа: -->
        <!-- border-top: создаёт тонкую линию сверху блока -->
        <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
        <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
        <footer class="border-top text-center py-3">
          {% include 'includes/footer.html' %}
        </footer>
    </div>
  </body>
</html>

yatube/templates/includes/footer.html
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>2024 GPL <span style="color:red">Ya</span>tube</p>    

yatube/templates/includes/header.html
{% load static%}
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar bg-body-tertiary">
        <div class="container">
          <a
            class="navbar-brand"
            href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
              <div class="form-check form-switch mx-4">
                <input
                  class="form-check-input p-2"
                  type="checkbox"
                  role="switch"
                  id="flexSwitchCheckChecked"
                  checked
                  onclick="myFunction()"
                />
              </div>
        </div>
      </nav>      

yatube/templates/posts/group_list.html
<!-- templates/group_list.html -->                   
{% extends 'base.html' %}

{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
<h1>{% block title %} Посты группы {{ group.title|title }} {% endblock %}</h1>

{% for group in posts %}
  <ul>
    <li>
      Автор: {{ group.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ group.pub_date|date:"d E Y" }}
    </li>
  </ul>
    <p>{{ group.text }}</p>

    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}

  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">     
    <h1>{% block title %} Latest posts {% endblock %}</h1>
    <article>
      {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
    {% if post.group %}   
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
    </article>
    <!-- под последним постом нет линии -->
  </div>
{% endblock %}